const collectionDataSample = {
    "items": [
    {
        "collid": "83235185",
        "versionid": null,
        "objecttype": "thing",
        "objectid": "232830",
        "imageid": null,
        "publisherid": null,
        "languageid": null,
        "year": null,
        "other": null,
        "barcode": null,
        "user": {
            "username": "TheCookieCats",
            "avatar": "1",
            "avatarfile": "avatar_id213497.jpg",
            "country": "United States",
            "city": "Oakton",
            "state": "Virginia",
            "avatarurl_md": "https://cf.geekdo-images.com/VE7g0YBNwVushhqHtA0pDjGwFd0=/35x35/filters:strip_icc()/https%3A%2F%2Fcf.geekdo-static.com%2Favatars%2Favatar_id213497.jpg",
            "microbadges": [
                {
                    "badgeid": "34410",
                    "userid": "971817",
                    "tstamp": "2015-01-28 13:02:36",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_34410_0.gif",
                    "slot": "1",
                    "id": "7824745",
                    "name": "Platinum Board Game Collector",
                    "filename": "",
                    "extension": "gif",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Board Game Collector",
                    "mouseover": "Platinum Board Game Collector",
                    "cost": "0",
                    "private": "1",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "45",
                    "coupon": "0",
                    "username": "",
                    "numsold": "6388",
                    "newfn": "1"
                },
                {
                    "badgeid": "49122",
                    "userid": "5799",
                    "tstamp": "2020-02-02 04:25:28",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_49122_0.gif",
                    "slot": "2",
                    "id": "10798956",
                    "name": "I was here for BGG's Twentieth Anniversary!",
                    "filename": "",
                    "extension": "gif",
                    "animated": "1",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "I was here for a BGG Anniversary!",
                    "mouseover": "I was here for BGG's Twentieth Anniversary!",
                    "cost": "0",
                    "private": "1",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "540",
                    "coupon": "0",
                    "username": "",
                    "numsold": "2482365",
                    "newfn": "1"
                },
                {
                    "badgeid": "39457",
                    "userid": "254870",
                    "tstamp": "2016-06-12 19:45:00",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_39457_0.png",
                    "slot": "3",
                    "id": "11669931",
                    "name": "Oniverse board game series fan",
                    "filename": "",
                    "extension": "png",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Oniverse board game series fan",
                    "mouseover": "Oniverse fan",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "1183",
                    "coupon": "0",
                    "username": "",
                    "numsold": "307",
                    "newfn": "1"
                },
                {
                    "badgeid": "3296",
                    "userid": "40311",
                    "tstamp": "0000-00-00 00:00:00",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_3296_0.gif",
                    "slot": "4",
                    "id": "13552716",
                    "name": "Ghostbusters fan (\"Who ya gonna call?\")",
                    "filename": "ghostbustersfan.gif",
                    "extension": "gif",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Ghostbusters fan",
                    "mouseover": "Who ya gonna call?",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "Pop Culture",
                    "subgroup": "Movies",
                    "groupid": "55",
                    "coupon": "0",
                    "username": "jeffwolfe",
                    "numsold": "558",
                    "newfn": "1"
                },
                {
                    "badgeid": "47624",
                    "userid": "729550",
                    "tstamp": "2019-07-20 00:34:18",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_47624_0.png",
                    "slot": "5",
                    "id": "13563813",
                    "name": "Silver fan",
                    "filename": "",
                    "extension": "png",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Silver",
                    "mouseover": "Silver fan",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "30",
                    "coupon": "0",
                    "username": "",
                    "numsold": "43",
                    "newfn": "1"
                }
            ],
            "flagimgurl": "https://cf.geekdo-static.com/images/flags/16x16/shadow/flag_usa.png"
        },
        "objectname": "Shifty Eyed Spies",
        "sunglasses": null,
        "images": {
            "micro": "https://cf.geekdo-images.com/J8GvDIigfMdxT9MoMHR01Q__micro/img/hen3OVaYR7zVVekTvmtyMJck1Bo=/fit-in/64x64/filters:strip_icc()/pic4372703.jpg",
            "thumb": "https://cf.geekdo-images.com/J8GvDIigfMdxT9MoMHR01Q__thumb/img/EWVfiXLL6HFexzDlxXNU_Q386sI=/fit-in/200x150/filters:strip_icc()/pic4372703.jpg"
        },
        "status": {
            "own": true,
            "fortrade": true
        },
        "status_tstamp": "2025-04-05 08:43:26",
        "wishlistpriority": 3,
        "pp_currency": null,
        "pricepaid": null,
        "cv_currency": null,
        "currvalue": null,
        "quantity": null,
        "acquisitiondate": null,
        "acquiredfrom": null,
        "privatecomment": null,
        "invdate": null,
        "invlocation": null,
        "textfield": {
            "privatecomment": {
                "value": null,
                "rendered": ""
            },
            "comment": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "conditiontext": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "wantpartslist": {
                "value": "Bookstore / newsstand location, 1 binoculars token, briefcase player marker",
                "tstamp": null,
                "rendered": "Bookstore / newsstand location, 1 binoculars token, briefcase player marker"
            },
            "haspartslist": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "wishlistcomment": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "customname": {
                "value": null,
                "tstamp": null,
                "rendered": null
            }
        },
        "rating": 0,
        "rating_tstamp": "0000-00-00 00:00:00",
        "tstamp": "2025-04-05 08:43:26",
        "postdate": "2021-06-21 00:32:10",
        "lastmodified": "2025-04-19 17:34:22",
        "comment_tstamp": "0000-00-00 00:00:00",
        "review_tstamp": null
    },
    {
        "collid": "83235199",
        "versionid": null,
        "objecttype": "thing",
        "objectid": "232830",
        "imageid": null,
        "publisherid": null,
        "languageid": null,
        "year": null,
        "other": null,
        "barcode": null,
        "user": {
            "username": "TheCookieCats",
            "avatar": "1",
            "avatarfile": "avatar_id213497.jpg",
            "country": "United States",
            "city": "Oakton",
            "state": "Virginia",
            "avatarurl_md": "https://cf.geekdo-images.com/VE7g0YBNwVushhqHtA0pDjGwFd0=/35x35/filters:strip_icc()/https%3A%2F%2Fcf.geekdo-static.com%2Favatars%2Favatar_id213497.jpg",
            "microbadges": [
                {
                    "badgeid": "34410",
                    "userid": "971817",
                    "tstamp": "2015-01-28 13:02:36",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_34410_0.gif",
                    "slot": "1",
                    "id": "7824745",
                    "name": "Platinum Board Game Collector",
                    "filename": "",
                    "extension": "gif",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Board Game Collector",
                    "mouseover": "Platinum Board Game Collector",
                    "cost": "0",
                    "private": "1",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "45",
                    "coupon": "0",
                    "username": "",
                    "numsold": "6388",
                    "newfn": "1"
                },
                {
                    "badgeid": "49122",
                    "userid": "5799",
                    "tstamp": "2020-02-02 04:25:28",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_49122_0.gif",
                    "slot": "2",
                    "id": "10798956",
                    "name": "I was here for BGG's Twentieth Anniversary!",
                    "filename": "",
                    "extension": "gif",
                    "animated": "1",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "I was here for a BGG Anniversary!",
                    "mouseover": "I was here for BGG's Twentieth Anniversary!",
                    "cost": "0",
                    "private": "1",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "540",
                    "coupon": "0",
                    "username": "",
                    "numsold": "2482365",
                    "newfn": "1"
                },
                {
                    "badgeid": "39457",
                    "userid": "254870",
                    "tstamp": "2016-06-12 19:45:00",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_39457_0.png",
                    "slot": "3",
                    "id": "11669931",
                    "name": "Oniverse board game series fan",
                    "filename": "",
                    "extension": "png",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Oniverse board game series fan",
                    "mouseover": "Oniverse fan",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "1183",
                    "coupon": "0",
                    "username": "",
                    "numsold": "307",
                    "newfn": "1"
                },
                {
                    "badgeid": "3296",
                    "userid": "40311",
                    "tstamp": "0000-00-00 00:00:00",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_3296_0.gif",
                    "slot": "4",
                    "id": "13552716",
                    "name": "Ghostbusters fan (\"Who ya gonna call?\")",
                    "filename": "ghostbustersfan.gif",
                    "extension": "gif",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Ghostbusters fan",
                    "mouseover": "Who ya gonna call?",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "Pop Culture",
                    "subgroup": "Movies",
                    "groupid": "55",
                    "coupon": "0",
                    "username": "jeffwolfe",
                    "numsold": "558",
                    "newfn": "1"
                },
                {
                    "badgeid": "47624",
                    "userid": "729550",
                    "tstamp": "2019-07-20 00:34:18",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_47624_0.png",
                    "slot": "5",
                    "id": "13563813",
                    "name": "Silver fan",
                    "filename": "",
                    "extension": "png",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Silver",
                    "mouseover": "Silver fan",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "30",
                    "coupon": "0",
                    "username": "",
                    "numsold": "43",
                    "newfn": "1"
                }
            ],
            "flagimgurl": "https://cf.geekdo-static.com/images/flags/16x16/shadow/flag_usa.png"
        },
        "objectname": "Shifty Eyed Spies",
        "sunglasses": null,
        "images": {
            "micro": "https://cf.geekdo-images.com/J8GvDIigfMdxT9MoMHR01Q__micro/img/hen3OVaYR7zVVekTvmtyMJck1Bo=/fit-in/64x64/filters:strip_icc()/pic4372703.jpg",
            "thumb": "https://cf.geekdo-images.com/J8GvDIigfMdxT9MoMHR01Q__thumb/img/EWVfiXLL6HFexzDlxXNU_Q386sI=/fit-in/200x150/filters:strip_icc()/pic4372703.jpg"
        },
        "status": {
            "own": true,
            "fortrade": true
        },
        "status_tstamp": "2025-04-05 08:43:27",
        "wishlistpriority": 3,
        "pp_currency": null,
        "pricepaid": null,
        "cv_currency": null,
        "currvalue": null,
        "quantity": null,
        "acquisitiondate": null,
        "acquiredfrom": null,
        "privatecomment": null,
        "invdate": null,
        "invlocation": null,
        "textfield": {
            "privatecomment": {
                "value": null,
                "rendered": ""
            },
            "comment": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "conditiontext": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "wantpartslist": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "haspartslist": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "wishlistcomment": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "customname": {
                "value": null,
                "tstamp": null,
                "rendered": null
            }
        },
        "rating": 0,
        "rating_tstamp": "0000-00-00 00:00:00",
        "tstamp": "2025-04-05 08:43:27",
        "postdate": "2021-06-21 00:32:49",
        "lastmodified": "2025-04-05 08:43:27",
        "comment_tstamp": "0000-00-00 00:00:00",
        "review_tstamp": null
    },
    {
        "collid": "131514664",
        "versionid": "364805",
        "objecttype": "thing",
        "objectid": "232830",
        "version": {
            "objecttype": "version",
            "objectid": "364805",
            "versionname": "Big G English edition",
            "linkedname": "Shifty Eyed Spies",
            "name": "Shifty Eyed Spies (Big G English edition)",
            "yearpublished": "2017",
            "href": "/boardgameversion/364805/big-g-english-edition",
            "images": {
                "micro": "https://cf.geekdo-images.com/_ilCUjTsc0SGoouv9u9zHw__micro/img/8Fr3PRKIMQOV8iNyIaLqL8Q1C3E=/fit-in/64x64/filters:strip_icc()/pic3686323.jpg",
                "thumb": "https://cf.geekdo-images.com/_ilCUjTsc0SGoouv9u9zHw__thumb/img/epp1n5TwbzGg468wTc52XwAJxIs=/fit-in/200x150/filters:strip_icc()/pic3686323.jpg"
            }
        },
        "imageid": null,
        "publisherid": null,
        "languageid": null,
        "year": null,
        "other": null,
        "barcode": null,
        "user": {
            "username": "TheCookieCats",
            "avatar": "1",
            "avatarfile": "avatar_id213497.jpg",
            "country": "United States",
            "city": "Oakton",
            "state": "Virginia",
            "avatarurl_md": "https://cf.geekdo-images.com/VE7g0YBNwVushhqHtA0pDjGwFd0=/35x35/filters:strip_icc()/https%3A%2F%2Fcf.geekdo-static.com%2Favatars%2Favatar_id213497.jpg",
            "microbadges": [
                {
                    "badgeid": "34410",
                    "userid": "971817",
                    "tstamp": "2015-01-28 13:02:36",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_34410_0.gif",
                    "slot": "1",
                    "id": "7824745",
                    "name": "Platinum Board Game Collector",
                    "filename": "",
                    "extension": "gif",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Board Game Collector",
                    "mouseover": "Platinum Board Game Collector",
                    "cost": "0",
                    "private": "1",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "45",
                    "coupon": "0",
                    "username": "",
                    "numsold": "6388",
                    "newfn": "1"
                },
                {
                    "badgeid": "49122",
                    "userid": "5799",
                    "tstamp": "2020-02-02 04:25:28",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_49122_0.gif",
                    "slot": "2",
                    "id": "10798956",
                    "name": "I was here for BGG's Twentieth Anniversary!",
                    "filename": "",
                    "extension": "gif",
                    "animated": "1",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "I was here for a BGG Anniversary!",
                    "mouseover": "I was here for BGG's Twentieth Anniversary!",
                    "cost": "0",
                    "private": "1",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "540",
                    "coupon": "0",
                    "username": "",
                    "numsold": "2482365",
                    "newfn": "1"
                },
                {
                    "badgeid": "39457",
                    "userid": "254870",
                    "tstamp": "2016-06-12 19:45:00",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_39457_0.png",
                    "slot": "3",
                    "id": "11669931",
                    "name": "Oniverse board game series fan",
                    "filename": "",
                    "extension": "png",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Oniverse board game series fan",
                    "mouseover": "Oniverse fan",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "1183",
                    "coupon": "0",
                    "username": "",
                    "numsold": "307",
                    "newfn": "1"
                },
                {
                    "badgeid": "3296",
                    "userid": "40311",
                    "tstamp": "0000-00-00 00:00:00",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_3296_0.gif",
                    "slot": "4",
                    "id": "13552716",
                    "name": "Ghostbusters fan (\"Who ya gonna call?\")",
                    "filename": "ghostbustersfan.gif",
                    "extension": "gif",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Ghostbusters fan",
                    "mouseover": "Who ya gonna call?",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "Pop Culture",
                    "subgroup": "Movies",
                    "groupid": "55",
                    "coupon": "0",
                    "username": "jeffwolfe",
                    "numsold": "558",
                    "newfn": "1"
                },
                {
                    "badgeid": "47624",
                    "userid": "729550",
                    "tstamp": "2019-07-20 00:34:18",
                    "active": "1",
                    "url": "https://cf.geekdo-static.com/mbs/mb_47624_0.png",
                    "slot": "5",
                    "id": "13563813",
                    "name": "Silver fan",
                    "filename": "",
                    "extension": "png",
                    "animated": "0",
                    "version": "0",
                    "badgestatus": "approved",
                    "desc": "Silver",
                    "mouseover": "Silver fan",
                    "cost": "0",
                    "private": "0",
                    "customurl": "0",
                    "baseurl": "",
                    "group": "",
                    "subgroup": "",
                    "groupid": "30",
                    "coupon": "0",
                    "username": "",
                    "numsold": "43",
                    "newfn": "1"
                }
            ],
            "flagimgurl": "https://cf.geekdo-static.com/images/flags/16x16/shadow/flag_usa.png"
        },
        "linkedname": "Shifty Eyed Spies",
        "name": "Big G English edition",
        "objectname": "Shifty Eyed Spies",
        "sunglasses": null,
        "images": {
            "micro": "https://cf.geekdo-images.com/_ilCUjTsc0SGoouv9u9zHw__micro/img/8Fr3PRKIMQOV8iNyIaLqL8Q1C3E=/fit-in/64x64/filters:strip_icc()/pic3686323.jpg",
            "thumb": "https://cf.geekdo-images.com/_ilCUjTsc0SGoouv9u9zHw__thumb/img/epp1n5TwbzGg468wTc52XwAJxIs=/fit-in/200x150/filters:strip_icc()/pic3686323.jpg"
        },
        "status": {
            "own": true,
            "wanttoplay": true,
            "preordered": true
        },
        "status_tstamp": "2025-04-19 17:35:53",
        "wishlistpriority": 3,
        "pp_currency": "USD",
        "pricepaid": 4,
        "cv_currency": null,
        "currvalue": null,
        "quantity": null,
        "acquisitiondate": "2025-04-19",
        "acquiredfrom": "SuperGLS (James!",
        "privatecomment": "Had bad briefcase token but that will be swapped out into the worst copy we have.",
        "invdate": "2025-04-19",
        "invlocation": null,
        "textfield": {
            "privatecomment": {
                "value": "Had bad briefcase token but that will be swapped out into the worst copy we have.",
                "rendered": "Had bad briefcase token but that will be swapped out into the worst copy we have."
            },
            "comment": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "conditiontext": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "wantpartslist": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "haspartslist": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "wishlistcomment": {
                "value": null,
                "tstamp": null,
                "rendered": null
            },
            "customname": {
                "value": null,
                "tstamp": null,
                "rendered": null
            }
        },
        "rating": 0,
        "rating_tstamp": "0000-00-00 00:00:00",
        "tstamp": "2025-04-19 17:35:53",
        "postdate": "2025-04-19 17:35:53",
        "lastmodified": "2025-04-19 17:35:54",
        "comment_tstamp": "0000-00-00 00:00:00",
        "review_tstamp": null
    }
]
}