ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
overrides:
  '@react-barcode-scanner/components': link:../../../Library/pnpm/global/5/node_modules/@react-barcode-scanner/components
