/**
 * Utility functions to transform autogenerated form field keys in @bpmn-io/form-js schemas
 * to meaningful label-based keys during save operations.
 */

export type FormComponent = {
    key: string;
    label?: string;
    type: string;
    children?: FormComponent[];
    components?: FormComponent[];
    [key: string]: unknown;
};

export type FormSchema = {
    id: string;
    type: string;
    components?: FormComponent[];
    [key: string]: unknown;
};

const slugify = (label: string) => label
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '') // Remove special chars except word chars, spaces, hyphens
    .replace(/\s+/g, '-')      // Replace spaces with hyphens
    .replace(/-+/g, '-')       // Collapse multiple hyphens
    .replace(/^-+|-+$/g, ''); // Trim hyphens from start/end

const makeUnique = (element: string, existing: Set<string>) => {
    if (!element) {
        return undefined;
    }
    let unique = element;
    let counter = 0;
    while (existing.has(unique) && counter <= Number.MAX_SAFE_INTEGER) {
        counter++;
        unique = `${element}--${counter}`;
    }
    return existing.has(unique) ? undefined : unique;
};

/**
 * Detects if a key is autogenerated by @bpmn-io/form-js.
 * Autogenerated keys follow the pattern: `${type}_${randomString}`
 * e.g., "textfield_abc123" or "checkbox_xyz789"
 *
 * @param type - The component type (e.g., "textfield", "checkbox")
 * @param key - The key to test
 * @returns true if the key appears to be autogenerated
 */
export const isAutogeneratedKey = (type: string, key: string): boolean => {
    return key.startsWith(`${type}_`) && key.length === type.length + 6;
};

/**
 * Converts a field label to a slugified key suitable for forms.
 * Handles spaces, special characters, and preserves semantic meaning.
 *
 * @param label - The field label to convert
 * @param usedKeys - Set of already-used keys to handle duplicates
 * @returns A slugified key, or empty string if label is empty/falsy
 */
export const generateKeyFromLabel = (key: string, label: string | undefined, usedKeys: Set<string> = new Set()): string => {
    if (!label) {
        return key;
    }

    // Convert to lowercase, remove special chars, replace spaces with hyphens
    let slug = makeUnique(slugify(label), usedKeys);

    if (!slug) {
        return key;
    }
    return slug;
};

/**
 * Recursively transforms autogenerated form field keys in a schema to label-based keys.
 * Mutates the schema components in-place.
 *
 * @param schema - The form schema to transform
 * @returns The transformed schema (same object, mutated)
 */
export const transformSchemaKeys = (schema: FormSchema): FormSchema => {
    const usedKeys = new Set<string>();

    const transformComponent = (component: FormComponent): void => {
        // Transform this component's key if it's autogenerated
        if (isAutogeneratedKey(component.type, component.key)) {
            component.key = generateKeyFromLabel(component.key,
                component.label as string,
                usedKeys) ?? component.key;
        }
        usedKeys.add(component.key);

        // Recursively transform nested components
        const nestedComponents = component.children ?? component.components ?? [];
        if (Array.isArray(nestedComponents)) {
            nestedComponents.forEach(child => transformComponent(child));
        }
    };

    // Transform all top-level components
    if (Array.isArray(schema.components)) {
        schema.components.forEach(component => transformComponent(component));
    }

    return schema;
};



