import { describe, it, expect } from '../setup.js';
import {
    isAutogeneratedKey,
    generateKeyFromLabel,
    transformSchemaKeys,
    type FormSchema,
    type FormComponent,
} from '@/app/lib/utils/formKeyTransform';

describe('formKeyTransform utils', () => {
    describe('#isAutogeneratedKey', () => {
        it('returns true when key starts with type and has at least 5 extra chars', () => {
            expect(isAutogeneratedKey('textfield', 'textfield_abc12')).toBe(true);
        });

        it('returns false when the key does not start with the type', () => {
            expect(isAutogeneratedKey('textfield', 'checkbox_abc12')).toBe(false);
        });

        it('returns false when the suffix is shorter than 5 chars (plus underscore)', () => {
            // type length = 9, key = 'textfield_ab' (length 12 < 9+6=15)
            expect(isAutogeneratedKey('textfield', 'textfield_ab')).toBe(false);
        });

        it('returns true for other component types', () => {
            expect(isAutogeneratedKey('checkbox', 'checkbox_xyz78')).toBe(true);
        });

        it('returns false when key equals exactly the type (no underscore)', () => {
            expect(isAutogeneratedKey('textfield', 'textfield')).toBe(false);
        });
    });

    describe('#generateKeyFromLabel', () => {
        it('slugifies a label into a key', () => {
            const result = generateKeyFromLabel('textfield_abc12', 'My Field Label', new Set());
            expect(result).toEqual('my-field-label');
        });

        it('returns the original key when label is empty', () => {
            const result = generateKeyFromLabel('textfield_abc12', '');
            expect(result).toEqual('textfield_abc12');
        });

        it('returns the original key when label is undefined', () => {
            const result = generateKeyFromLabel('textfield_abc12', undefined);
            expect(result).toEqual('textfield_abc12');
        });

        it('de-duplicates keys by appending a counter', () => {
            const used = new Set(['my-label']);
            const result = generateKeyFromLabel('textfield_abc12', 'My Label', used);
            expect(result).toEqual('my-label--1');
        });

        it('strips special characters from the label', () => {
            const result = generateKeyFromLabel('key', 'Hello, World!', new Set());
            expect(result).toEqual('hello-world');
        });

        it('trims leading and trailing hyphens from the slug', () => {
            const result = generateKeyFromLabel('key', '  --hello--  ', new Set());
            expect(result).toEqual('hello');
        });
    });

    describe('#transformSchemaKeys', () => {
        it('transforms an autogenerated key to a label-based slug', () => {
            // Arrange
            const schema: FormSchema = {
                id: 'form-1',
                type: 'default',
                components: [
                    {
                        key: 'textfield_abc12',
                        label: 'Player Name',
                        type: 'textfield',
                    },
                ],
            };

            // Act
            const result = transformSchemaKeys(schema);

            // Assert
            expect(result.components?.[0].key).toEqual('player-name');
        });

        it('leaves manually-set (non-autogenerated) keys unchanged', () => {
            const schema: FormSchema = {
                id: 'form-2',
                type: 'default',
                components: [
                    {
                        key: 'my-custom-key',
                        label: 'Custom',
                        type: 'textfield',
                    },
                ],
            };
            transformSchemaKeys(schema);
            expect(schema.components?.[0].key).toEqual('my-custom-key');
        });

        it('handles nested components via the children property', () => {
            const schema: FormSchema = {
                id: 'form-3',
                type: 'default',
                components: [
                    {
                        key: 'group_xyz78',
                        type: 'group',
                        children: [
                            {
                                key: 'textfield_def45',
                                label: 'Email',
                                type: 'textfield',
                            },
                        ],
                    },
                ],
            };
            transformSchemaKeys(schema);
            const child = (schema.components?.[0].children as FormComponent[])?.[0];
            expect(child?.key).toEqual('email');
        });

        it('handles nested components via the components property', () => {
            const schema: FormSchema = {
                id: 'form-4',
                type: 'default',
                components: [
                    {
                        key: 'group_xyz78',
                        type: 'group',
                        components: [
                            {
                                key: 'textfield_def45',
                                label: 'Phone',
                                type: 'textfield',
                            },
                        ],
                    },
                ],
            };
            transformSchemaKeys(schema);
            const child = (schema.components?.[0].components as FormComponent[])?.[0];
            expect(child?.key).toEqual('phone');
        });

        it('de-duplicates sibling keys that would collide after slugification', () => {
            const schema: FormSchema = {
                id: 'form-5',
                type: 'default',
                components: [
                    { key: 'textfield_aaa11', label: 'Name', type: 'textfield' },
                    { key: 'textfield_bbb22', label: 'Name', type: 'textfield' },
                ],
            };
            transformSchemaKeys(schema);
            const keys = schema.components?.map(c => c.key);
            expect(keys?.[0]).toEqual('name');
            expect(keys?.[1]).toEqual('name--1');
        });

        it('returns the schema object (same reference)', () => {
            const schema: FormSchema = { id: 'form-6', type: 'default', components: [] };
            const result = transformSchemaKeys(schema);
            expect(result).toBe(schema);
        });

        it('handles a schema with no components gracefully', () => {
            const schema: FormSchema = { id: 'form-7', type: 'default' };
            expect(() => transformSchemaKeys(schema)).not.toThrow();
        });
    });
});
